/* Dream Mall '27 — catalogue & cost data.
   Edit prices, items, icons (e:) and essential living costs here. */

/* ---------------- Data ---------------- */
// price = cost per unit (INR). mult = annual multiplier (12 for monthly things). unit = label.
const CATS = [
  {ico:"👔", name:"Fashion & Style", tint:"rgba(255,46,147,.30)", items:[
    {n:"Premium sneakers (Nike/Jordan)",p:12000,u:"per pair",e:"👟"},
    {n:"Formal shoes",p:6000,u:"per pair",e:"👞"},
    {n:"Branded shirts",p:2800,u:"each",e:"👔"},
    {n:"Premium t-shirts",p:1800,u:"each",e:"👕"},
    {n:"Jeans / chinos",p:3500,u:"each",e:"👖"},
    {n:"Jacket / hoodie",p:5000,u:"each",e:"🧥"},
    {n:"Watch",p:25000,u:"each",e:"⌚"},
    {n:"Sunglasses (Ray-Ban)",p:8000,u:"each",e:"🕶️"},
    {n:"Tailored suit",p:20000,u:"each",e:"🤵"},
    {n:"Ethnic wear (weddings)",p:15000,u:"each",e:"🥻"},
    {n:"Perfume / cologne",p:7000,u:"each",e:"🧴"},
    {n:"Salon & grooming",p:1200,u:"per visit",e:"💈"},
  ]},
  {ico:"📱", name:"Gadgets & Tech", tint:"rgba(141,120,255,.32)", items:[
    {n:"Latest iPhone",p:130000,u:"each",e:"📱"},
    {n:"MacBook / laptop",p:150000,u:"each",e:"💻"},
    {n:"iPad / tablet",p:60000,u:"each",e:"📲"},
    {n:"Apple Watch / smartwatch",p:45000,u:"each",e:"⌚"},
    {n:"AirPods / wireless earbuds",p:24000,u:"each",e:"🎧"},
    {n:"Premium headphones",p:30000,u:"each",e:"🎵"},
    {n:"Gaming console (PS5)",p:55000,u:"each",e:"🎮"},
    {n:"Mechanical keyboard",p:9000,u:"each",e:"⌨️"},
    {n:"Extra monitor",p:25000,u:"each",e:"🖥️"},
    {n:"Streaming + cloud + apps",p:1000,u:"per month",mult:12,e:"📺"},
  ]},
  {ico:"📸", name:"Photo & Content", tint:"rgba(67,233,192,.28)", items:[
    {n:"Mirrorless camera",p:150000,u:"each",e:"📷"},
    {n:"Extra lens",p:55000,u:"each",e:"🔭"},
    {n:"Drone",p:80000,u:"each",e:"🚁"},
    {n:"Action camera (GoPro)",p:45000,u:"each",e:"📹"},
    {n:"Gimbal",p:25000,u:"each",e:"🎥"},
    {n:"Tripod",p:8000,u:"each",e:"🎬"},
    {n:"Editing software",p:6000,u:"per year",e:"🎞️"},
    {n:"Photography workshop",p:15000,u:"each",e:"📸"},
  ]},
  {ico:"🏍️", name:"Bikes & Cars", tint:"rgba(255,201,77,.30)", items:[
    {n:"Motorcycle EMI",p:6000,u:"per month",mult:12,e:"🏍️"},
    {n:"Full riding gear (helmet/jacket/boots)",p:40000,u:"set",e:"🪖"},
    {n:"Bike servicing",p:8000,u:"per year",e:"🔧"},
    {n:"Fuel",p:3500,u:"per month",mult:12,e:"⛽"},
    {n:"Car EMI",p:18000,u:"per month",mult:12,e:"🚗"},
    {n:"Car accessories",p:20000,u:"per year",e:"🛠️"},
    {n:"Road trips",p:25000,u:"per trip",e:"🛣️"},
    {n:"Parking & tolls",p:1200,u:"per month",mult:12,e:"🅿️"},
  ]},
  {ico:"✈️", name:"Travel & Adventure", tint:"rgba(80,180,255,.30)", items:[
    {n:"Domestic flight + hotel trip",p:25000,u:"per trip",e:"✈️"},
    {n:"Resort / beach getaway",p:40000,u:"per trip",e:"🏖️"},
    {n:"Trek / wildlife safari",p:25000,u:"per trip",e:"🏕️"},
    {n:"Thailand / Bali / Vietnam trip",p:100000,u:"per trip",e:"🏝️"},
    {n:"Dubai trip",p:120000,u:"per trip",e:"🏙️"},
    {n:"Europe trip",p:300000,u:"per trip",e:"🏰"},
    {n:"Japan trip",p:250000,u:"per trip",e:"🗻"},
    {n:"USA / Australia trip",p:380000,u:"per trip",e:"🗽"},
    {n:"Shopping abroad",p:50000,u:"per trip",e:"🛍️"},
  ]},
  {ico:"🍽️", name:"Food & Dining", tint:"rgba(255,140,90,.30)", items:[
    {n:"Fine dining dinner",p:4000,u:"per meal",e:"🍽️"},
    {n:"Weekend brunch / rooftop",p:2500,u:"per outing",e:"🥂"},
    {n:"Specialty coffee runs",p:2500,u:"per month",mult:12,e:"☕"},
    {n:"Food delivery (Swiggy/Zomato)",p:8000,u:"per month",mult:12,e:"🥡"},
    {n:"Celebration dinner",p:6000,u:"each",e:"🍾"},
    {n:"Cooking / wine workshop",p:4500,u:"each",e:"👨‍🍳"},
  ]},
  {ico:"🎉", name:"Going Out & Events", tint:"rgba(255,46,147,.28)", items:[
    {n:"Movies",p:1400,u:"per outing",e:"🍿"},
    {n:"Concert / live show",p:8000,u:"per ticket",e:"🎤"},
    {n:"Stand-up comedy",p:2000,u:"per show",e:"🎙️"},
    {n:"Music festival",p:15000,u:"each",e:"🎶"},
    {n:"Theme park / sports event",p:5000,u:"per outing",e:"🎢"},
    {n:"Weekend party night",p:4000,u:"per night",e:"🥳"},
    {n:"Friend's wedding (gift+travel+outfit)",p:15000,u:"per wedding",e:"💒"},
    {n:"Bachelor / bachelorette trip",p:30000,u:"each",e:"🎉"},
  ]},
  {ico:"💪", name:"Health & Fitness", tint:"rgba(67,233,192,.30)", items:[
    {n:"Premium gym membership",p:40000,u:"per year",e:"🏋️"},
    {n:"Personal trainer",p:5000,u:"per month",mult:12,e:"💪"},
    {n:"Yoga / swimming / club",p:2000,u:"per month",mult:12,e:"🧘"},
    {n:"Supplements",p:2000,u:"per month",mult:12,e:"💊"},
    {n:"Annual health checkup",p:8000,u:"per year",e:"🩺"},
    {n:"Marathon / sports gear",p:18000,u:"per year",e:"🏃"},
  ]},
  {ico:"🎮", name:"Hobbies", tint:"rgba(141,120,255,.30)", items:[
    {n:"New video games",p:15000,u:"per year",e:"🕹️"},
    {n:"Road / cycling bike",p:55000,u:"each",e:"🚴"},
    {n:"Guitar / instrument",p:25000,u:"each",e:"🎸"},
    {n:"Music lessons",p:2500,u:"per month",mult:12,e:"🎵"},
    {n:"Books",p:1000,u:"per month",mult:12,e:"📚"},
    {n:"Collectibles / board games",p:20000,u:"per year",e:"🎲"},
  ]},
  {ico:"🏠", name:"Home & Living", tint:"rgba(255,201,77,.26)", items:[
    {n:"Premium furniture",p:120000,u:"per year",e:"🛋️"},
    {n:"Smart home devices",p:35000,u:"per year",e:"💡"},
    {n:"Coffee machine",p:30000,u:"each",e:"☕"},
    {n:"Air purifier",p:18000,u:"each",e:"💨"},
    {n:"Home decor & plants",p:25000,u:"per year",e:"🪴"},
    {n:"House help / cleaning",p:3000,u:"per month",mult:12,e:"🧹"},
  ]},
  {ico:"📚", name:"Learning & Growth", tint:"rgba(80,180,255,.28)", items:[
    {n:"Online courses",p:18000,u:"per year",e:"🎓"},
    {n:"Certification",p:35000,u:"each",e:"📜"},
    {n:"Conference / workshop",p:20000,u:"each",e:"🗣️"},
    {n:"Coaching program",p:50000,u:"each",e:"🧑‍🏫"},
    {n:"Language learning",p:15000,u:"per year",e:"🌐"},
  ]},
  {ico:"💘", name:"Dating & Relationships", tint:"rgba(255,111,182,.32)", items:[
    {n:"Date nights",p:3500,u:"per month",mult:12,e:"💑"},
    {n:"Gifts for partner",p:18000,u:"per year",e:"🎁"},
    {n:"Anniversary / flowers",p:12000,u:"per year",e:"💐"},
    {n:"Couple weekend getaway",p:30000,u:"per trip",e:"💕"},
    {n:"Couple vacation",p:90000,u:"per trip",e:"🌴"},
  ]},
  {ico:"🎁", name:"Family & Festivals", tint:"rgba(255,201,77,.28)", items:[
    {n:"Gifts for parents",p:30000,u:"per year",e:"💝"},
    {n:"Gifts for siblings",p:15000,u:"per year",e:"🎀"},
    {n:"Festival shopping (Diwali etc.)",p:30000,u:"per year",e:"🪔"},
    {n:"Donations",p:15000,u:"per year",e:"🤲"},
    {n:"Family vacation",p:100000,u:"per trip",e:"👨‍👩‍👧‍👦"},
  ]},
  {ico:"🌟", name:"Luxury Flex", tint:"rgba(212,175,55,.34)", items:[
    {n:"Five-star hotel stay",p:50000,u:"per stay",e:"🏨"},
    {n:"Business class flight",p:180000,u:"each",e:"🛫"},
    {n:"Luxury spa day",p:15000,u:"each",e:"💆"},
    {n:"Golf membership",p:200000,u:"per year",e:"⛳"},
    {n:"Yacht / helicopter experience",p:60000,u:"each",e:"🛥️"},
    {n:"Luxury train journey",p:250000,u:"each",e:"🚂"},
  ]},
  {ico:"📈", name:"Status & Bling", tint:"rgba(255,46,147,.30)", items:[
    {n:"Gold purchase",p:100000,u:"per year",e:"🪙"},
    {n:"Luxury watch (Rolex)",p:1000000,u:"each",e:"⌚"},
    {n:"Designer brand (LV/Gucci)",p:150000,u:"each",e:"👜"},
    {n:"Premium memberships",p:50000,u:"per year",e:"🎫"},
  ]},
];

const ESSENTIALS = [
  {n:"Rent (decent place in the city)",m:22000},
  {n:"Groceries & home food",m:11000},
  {n:"Electricity, water, gas",m:3000},
  {n:"Phone & internet",m:2000},
  {n:"Daily commute / transport",m:4000},
  {n:"Health insurance & medical",m:2500},
];
const ESS_ANNUAL = ESSENTIALS.reduce((s,e)=>s+e.m*12,0);
const SAVINGS_RATE = 0.20;
